class FblaEventOption {
  final String name;
  final String category;

  const FblaEventOption(this.name, this.category);

  String get storageKey => '$category::$name';
}

const List<String> fblaEventCategories = [
  'All',
  'Presentation Events',
  'Roleplay Events',
  'Objective Test Events',
  'Production Events',
  'Virtual & Partner Challenges',
  'Chapter Events',
];

const List<FblaEventOption> fblaEventCatalog = [
  FblaEventOption('Broadcast Journalism', 'Presentation Events'),
  FblaEventOption('Business Ethics', 'Presentation Events'),
  FblaEventOption('Business Plan', 'Presentation Events'),
  FblaEventOption('Coding & Programming', 'Presentation Events'),
  FblaEventOption('Computer Game & Simulation Programming', 'Presentation Events'),
  FblaEventOption('Data Analysis', 'Presentation Events'),
  FblaEventOption('Digital Animation', 'Presentation Events'),
  FblaEventOption('Digital Video Production', 'Presentation Events'),
  FblaEventOption('Electronic Career Portfolio', 'Presentation Events'),
  FblaEventOption('Financial Planning', 'Presentation Events'),
  FblaEventOption('Financial Statement Analysis', 'Presentation Events'),
  FblaEventOption('Future Business Educator', 'Presentation Events'),
  FblaEventOption('Future Business Leader', 'Presentation Events'),
  FblaEventOption('Graphic Design', 'Presentation Events'),
  FblaEventOption('Impromptu Speaking', 'Presentation Events'),
  FblaEventOption('Introduction to Business Presentation', 'Presentation Events'),
  FblaEventOption('Introduction to Public Speaking', 'Presentation Events'),
  FblaEventOption('Introduction to Social Media Strategy', 'Presentation Events'),
  FblaEventOption('Job Interview', 'Presentation Events'),
  FblaEventOption('Mobile Application Development', 'Presentation Events'),
  FblaEventOption('Public Service Announcement', 'Presentation Events'),
  FblaEventOption('Public Speaking', 'Presentation Events'),
  FblaEventOption('Sales Presentation', 'Presentation Events'),
  FblaEventOption('Social Media Strategies', 'Presentation Events'),
  FblaEventOption('Visual Design', 'Presentation Events'),
  FblaEventOption('Website Design', 'Presentation Events'),
  FblaEventOption('Banking & Financial Systems', 'Roleplay Events'),
  FblaEventOption('Business Management', 'Roleplay Events'),
  FblaEventOption('Customer Service', 'Roleplay Events'),
  FblaEventOption('Entrepreneurship', 'Roleplay Events'),
  FblaEventOption('Hospitality & Event Management', 'Roleplay Events'),
  FblaEventOption('International Business', 'Roleplay Events'),
  FblaEventOption('Management Information Systems', 'Roleplay Events'),
  FblaEventOption('Marketing', 'Roleplay Events'),
  FblaEventOption('Network Design', 'Roleplay Events'),
  FblaEventOption('Parliamentary Procedure', 'Roleplay Events'),
  FblaEventOption('Sports & Entertainment Management', 'Roleplay Events'),
  FblaEventOption('Accounting I & II', 'Objective Test Events'),
  FblaEventOption('Advertising', 'Objective Test Events'),
  FblaEventOption('Agribusiness', 'Objective Test Events'),
  FblaEventOption('Business Communication', 'Objective Test Events'),
  FblaEventOption('Business Law', 'Objective Test Events'),
  FblaEventOption('Cybersecurity', 'Objective Test Events'),
  FblaEventOption('Data Science & AI', 'Objective Test Events'),
  FblaEventOption('Economics', 'Objective Test Events'),
  FblaEventOption('Financial Planning', 'Objective Test Events'),
  FblaEventOption('Healthcare Administration', 'Objective Test Events'),
  FblaEventOption('Insurance & Risk Management', 'Objective Test Events'),
  FblaEventOption('Introduction to Business Communication', 'Objective Test Events'),
  FblaEventOption('Introduction to Business Concepts', 'Objective Test Events'),
  FblaEventOption('Introduction to FBLA', 'Objective Test Events'),
  FblaEventOption('Journalism', 'Objective Test Events'),
  FblaEventOption('Organizational Leadership', 'Objective Test Events'),
  FblaEventOption('Personal Finance', 'Objective Test Events'),
  FblaEventOption('Supply Chain Management', 'Objective Test Events'),
  FblaEventOption('Computer Applications', 'Production Events'),
  FblaEventOption('Spreadsheet Applications', 'Production Events'),
  FblaEventOption('Word Processing', 'Production Events'),
  FblaEventOption('Virtual Business Finance Challenge', 'Virtual & Partner Challenges'),
  FblaEventOption('Virtual Business Management Challenge', 'Virtual & Partner Challenges'),
  FblaEventOption('FBLA Stock Market Game', 'Virtual & Partner Challenges'),
  FblaEventOption('LifeSmarts', 'Virtual & Partner Challenges'),
  FblaEventOption('American Enterprise Project', 'Chapter Events'),
  FblaEventOption('Community Service Project', 'Chapter Events'),
  FblaEventOption('Local Chapter Annual Business Report', 'Chapter Events'),
  FblaEventOption('Partnership with Business Project', 'Chapter Events'),
];
